### ISSUE TITLE
Dynamic line connecting not working for angular

### ISSUE THREAD

**Issue by RaviGuggilam** [II-alex-II/leader-line-new#7]
Dynamic rendering not working, below is the piece of code. Following packages are used for development ( "leader-line-new": "^1.1.9","ngx-leader-line": "^0.0.3")

xxxx.html
`<div
      #card{{i+1}}="ldrDest"
      ldrDest
      class="card custom-card"
      *ngFor="let data of details; let i = index"
    >
      <div class="card-header">Card {{ i + 1 }} Text</div>
      <div class="card-body">
        <button
          class="btn btn-secondary m-1"
          #start
          [ldrConnectTo]="button['targetCardNo']"
          *ngFor="let button of data.buttons"
        >
          {{ button.name }}
        </button>
      </div>
    </div>`
xxxx.json
export const dynamic = [
  {
    cardNo: 1,
    text: "Card No : 1",
    buttons: [
      { name: "Yes", questionId: "q1", targetCardNo: 2 },
      { name: "No", questionId: "q1", targetCardNo: 3 },
    ],
  },
  {
    cardNo: 2,
    text: "Card No: 2",
  },
  {
    cardNo: 3,
    text: "Card No: 2",
  },
];

**Comment by II-alex-II** [comment]
Hi, I see you use 2 packages "leader-line-new": "^1.1.9","ngx-leader-line": "^0.0.3". Why? I don`t understood you code. For dynamic rendering I used method "position" see documentation.
Good coding!

```position
self = line.position()
Re-position the leader line with current position and size of the elements as start or end option.
By default, the position of each leader line is fixed automatically when the window that loads LeaderLine was resized. You should call position method if your web page moved or resized the elements without resizing the window. For example, animation, a box that was scrolled or <iframe> that was resized.

scrollableBox.addEventListener('scroll', AnimEvent.add(function() {
  line.position();
}), false);```

**Comment by II-alex-II** [comment]
closed
